import { StyleSheet } from "react-native";
import { theme } from "@/shared/constants/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.light.mainBackground,
    // alignItems: "center",
    // justifyContent: "center",
  },
  imageContainer: {
    paddingHorizontal: 14,
    position: "relative",
  },
  imageWrapper: {
    width: "100%",
    height: 240,
    borderRadius: 30,
    overflow: "hidden",
    position: "relative",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  passedImage: {
    opacity: 0.82,
  },
  passedOverlayGray: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(110, 110, 110, 0.5)",
  },
  passedOverlayDark: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  passedEventMarker: {
    position: "absolute",
    top: 26,
    right: 24,
    backgroundColor: "#424242",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 39,
  },
  multiDayEventMarker: {
    position: "absolute",
    top: 26,
    right: 24,
    backgroundColor: theme.light.primary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 39,
  },
  passedText: {
    color: "white",
    fontSize: 14,
    fontWeight: "300",
    textAlign: "center",
  },
  positionButtons: {
    position: "absolute",
    bottom: -20,
    right: 34,
    gap: 12,
    flexDirection: "row",
  },
  positionBackButton: {
    position: "absolute",
    top: 26,
    left: 40,
  },
  detailsContainer: {
    paddingHorizontal: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: 600,
    marginTop: 40,
  },
  shortDesc: {
    fontSize: 16,
    fontWeight: 300,
    marginTop: 8,
  },
  dateAndTimeRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginTop: 20,
  },
  dateAndTimeColumnContainer: {
    flexDirection: "column",
    gap: 12,
    marginTop: 20,
  },
  locationRowContainerAndOrganizerRowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: "600",
    color: theme.light.dark_grey,
    marginTop: 30,
    marginBottom: 16,
  },
  bulletListContainer: {
    marginBottom: 0,
  },
  bulletListItem: {
    flexDirection: "row",
    marginBottom: 14,
    paddingRight: 16,
  },
  bulletPoint: {
    width: 10,
    height: 10,
    borderRadius: 3,
    backgroundColor: theme.light.dark_grey,
    marginTop: 7,
    marginRight: 8,
  },
  bulletText: {
    fontSize: 16,
    color: theme.light.dark_grey,
    fontWeight: "300",
    lineHeight: 22,
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 30
  },
  tagChip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
  },
  tagChipText: {
    fontSize: 14,
    fontWeight: "400",
  },
  stickyBottomContainer: {
    position: "absolute",
    bottom: 50,
    left: 0,
    right: 0,
    paddingHorizontal: 24,
    paddingVertical: 16,
    backgroundColor: "transparent",
  },
actionButton: {
    backgroundColor: theme.light.primary,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 56,
    width: '100%',
},
    actionButtonText: {
    color: theme.light.dark_grey,
    fontSize: 18,
    fontWeight: "400",
    textAlign: "center",
    lineHeight: 22,
},
  scrollContent: {
    paddingBottom: 140,
  },
});
